version: "3.7"

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MySQL
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - 5012:3306

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql-data:

#http://localhost:5013/ -> PhpMyAdmin
#    - Server=MySQL
#    - MYSQL_USER=admin
#    - MYSQL_PASSWORD=admin
