version: "3.7"

services:
  pgsql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PostgreSQL
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: PgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5011:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - pgsql:pgsql-server


volumes:
  pgsql-data:
  pgadmin-data:


#  http://localhost:5011/
#  docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' PostgreSQL
#  psql -h localhost -p 5432 -U admin -W -d furniture_reservation_system
#  \dt+